[workspace]
authors = ["curvesy <noobesang@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly/", "conda-forge"]
name = "ultimate_api_system"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=25.6.0.dev2025081405,<26"
fastapi = ">=0.116.1,<0.117"
uvicorn = ">=0.35.0,<0.36"
httptools = ">=0.6.4,<0.7"
watchfiles = ">=1.1.0,<2"
websockets = ">=15.0.1,<16"
pydantic = ">=2.11.7,<3"
httpx = ">=0.28.1,<0.29"
pytest = ">=8.4.1,<9"
pytest-asyncio = ">=1.1.0,<2"
numpy = ">=2.3.2,<3"
