apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aura-intelligence-production
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: aura-intelligence

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- storage.yaml
- redis-deployment.yaml
- aura-deployment.yaml
- hpa.yaml
- ingress.yaml
- monitoring.yaml

images:
- name: aura-intelligence
  newTag: v2025.1.0

commonLabels:
  app.kubernetes.io/instance: production
  app.kubernetes.io/managed-by: kustomize
  environment: production

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aura-intelligence
    namespace: aura-intelligence
  spec:
    template:
      metadata:
        annotations:
          deployment.kubernetes.io/revision: "1"
          config.kubernetes.io/depends-on: "aura-intelligence/redis,aura-intelligence/aura-config"